import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { FlatCompat } from '@eslint/eslintrc'

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) })

const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // next-env.d.ts is generated by Next on every build and gitignored;
    // its triple-slash references are not ours to fix.
    ignores: [
      '.next/**',
      'node_modules/**',
      'public/mediapipe/**',
      'test-results/**',
      'next-env.d.ts',
    ],
  },
  {
    // The production startup file is CommonJS, alone in this project.
    //
    // Managed Node panels start an app by filename, and `package.json` has no
    // `"type": "module"` — so an ESM server.js makes Node print a
    // MODULE_TYPELESS_PACKAGE_JSON warning and reparse it, at the very top of
    // the panel's log, which is often the only window into what the process
    // did. Adding `"type": "module"` would silence it by reclassifying every
    // `.js` file in the project, which is a lot of blast radius for a shim.
    files: ['server.js'],
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
]

export default config
