"""SHIVA entrypoint.

    python -m shiva              # full voice mode (standby → clap-clap "wake up")
    python -m shiva --text       # typed mode (no microphone — boots awake)

In any mode you can TYPE a command in the terminal and press Enter.
Pressing Enter on an empty line = push-to-talk (start listening now).
Typed controls: "wake" rises from standby, "shutdown" returns to it.
"""
import argparse
import asyncio
import contextlib
import datetime
import shutil
import subprocess
import sys
from pathlib import Path

from .bus import Bus
from .config import Config, deprecated_env
from .migrate import migrate_data
from .brain import Brain
from .ears import Ears
from .nandi import Nandi
from .shruti import Shruti
from .drishti import Drishti
from .smriti import Smriti
from .kaala import Kaala
from .sentinel import ClapDetector, Sentinel, is_sleep_phrase
from .tools_reminders import Reminders
from .voice import Voice
from .watchtower import Watchtower

BANNER = r"""
   ██████  ██████  ██ ███    ██
  ██    ██ ██   ██ ██ ████   ██
  ██    ██ ██   ██ ██ ██ ██  ██
  ██    ██ ██   ██ ██ ██  ██ ██
   ██████  ██████  ██ ██   ████   the all-knowing
"""

CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
# App-launched SHIVA gets a bare PATH (no /opt/homebrew/bin) — resolve absolutely.
FFPLAY = shutil.which("ffplay") or "/opt/homebrew/bin/ffplay"


def _greeting(name: str) -> str:
    now = datetime.datetime.now()
    tod = ("morning" if now.hour < 12 else "afternoon" if now.hour < 17 else "evening")
    return (f"Good {tod}, {name}. It's {now.strftime('%-I:%M')}. "
            "Shall I brief you?")


async def main() -> None:
    parser = argparse.ArgumentParser(prog="shiva")
    parser.add_argument("--text", action="store_true", help="typed mode, no microphone")
    args = parser.parse_args()

    print(BANNER)
    cfg = Config()

    # Carry data across the rebrand, once, and say so. These files hold the
    # face SHIVA was enrolled with, everything it has been asked to remember,
    # and your voiceprint — none of which can be regenerated by rerunning
    # anything, and all of which are gitignored, so a silent failure here would
    # first show up as SHIVA not knowing who you are.
    for moved in migrate_data(cfg.data_dir):
        print(f"[shiva] migrated {moved}")
    for name in deprecated_env():
        print(f"[shiva] {name} is the old name and still works — rename it in .env")

    bus = Bus(cfg)
    await bus.start()
    await bus.log(f"HUD → http://localhost:{cfg.hud_http_port}")

    smriti = Smriti(cfg)
    voice = Voice(cfg, bus)
    brain = Brain(cfg, bus, voice, smriti)
    await brain.start()

    # ── mode: asleep (standby, sentinel only) | awake (full senses) ────────
    state = {"mode": "asleep" if (cfg.standby and not args.text) else "awake"}
    awake = lambda: state["mode"] == "awake"  # noqa: E731

    reminders = Reminders(cfg, bus, brain, gate=awake)
    from .tools_mac import _CTX as _tool_ctx
    _tool_ctx["reminders"] = reminders

    watchtower = Watchtower(cfg, bus, brain)
    _tool_ctx["watchtower"] = watchtower

    kaala = Kaala(cfg, bus, brain, gate=awake)
    _tool_ctx["kaala"] = kaala

    from .vani import Vani
    vani = Vani(cfg) if cfg.vani_enabled else None
    clapdet = ClapDetector()   # shared: ears feeds it while awake

    # Voice mute: "stop" silences SHIVA's listening; "wake up" resumes it.
    muted = {"on": False}
    STOP_CUES = {"stop", "stop listening", "mute", "stop it", "be quiet"}
    WAKE_CUES = {"wake up", "wakeup", "wake", "start listening", "you awake"}

    # Session verification: voice + face once per day; camera-negative re-locks.
    verified = {"on": False, "date": None}

    def face_ok(window: float = 20.0) -> bool:
        s = brain.last_sighting
        return bool(s and "guest" not in s[0]
                    and (datetime.datetime.now() - s[1]).total_seconds() < window)

    # ── window choreography ────────────────────────────────────────────────
    def open_window(page: str) -> None:
        with contextlib.suppress(Exception):
            subprocess.Popen(
                [CHROME, f"--app=http://localhost:{cfg.hud_http_port}/{page}"],
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    def sanctum_missing() -> bool:
        try:
            import Quartz
            wins = Quartz.CGWindowListCopyWindowInfo(
                Quartz.kCGWindowListOptionAll, Quartz.kCGNullWindowID)
            return not any("SANCTUM" in (w.get("kCGWindowName") or "").upper()
                           for w in wins or [])
        except Exception:
            return True

    def close_aux_windows() -> None:
        script = ('tell application "Google Chrome"\n'
                  ' repeat with w in windows\n'
                  '  if (title of w contains "SHIVA") and (title of w does not contain "SANCTUM") then close w\n'
                  ' end repeat\nend tell')
        with contextlib.suppress(Exception):
            subprocess.run(["osascript", "-e", script], capture_output=True, timeout=10)

    # ── awake services (created per wake cycle so the mic/camera truly rest) ─
    svc: dict = {"ears": None, "nandi": None, "tasks": []}

    def identity_hint():
        s = brain.last_sighting
        if not s:
            return None
        name, ts = s
        if (datetime.datetime.now() - ts).total_seconds() > 15 or "guest" in name:
            return None
        return name

    def presence_hot() -> bool:
        s = brain.last_sighting
        return bool(cfg.open_mic and s
                    and (datetime.datetime.now() - s[1]).total_seconds() < 15
                    and "guest" not in s[0]
                    and not voice.busy()
                    and not brain.responding
                    and bus.current_state in ("idle", "listening"))

    def shiva_talking() -> bool:
        return voice.busy() or brain.responding

    async def on_utterance(text: str, speaker: str | None = None) -> None:
        if voice.echoes_recent(text):
            await bus.log("ears: dropped self-echo (matched SHIVA's recent speech)")
            if cfg.followup and svc["ears"]:
                await voice.wait_until_quiet()
                await asyncio.sleep(cfg.echo_settle)
                svc["ears"].trigger()
            return
        norm = text.lower().strip().strip(".,!?…-— ")

        # clap-clap + "shutdown" → back to standby (word alone never triggers)
        if is_sleep_phrase(norm) and (clapdet.pair_recent(4.0) or args.text):
            await sleep_sequence()
            return

        if muted["on"]:
            if norm in WAKE_CUES or "wake up" in norm:
                muted["on"] = False
                await bus.log("listening resumed (voice cue)")
                await voice.say("I'm awake, sir. Listening again.")
        elif norm in STOP_CUES:
            muted["on"] = True
            await voice.stop()
            await bus.log("listening muted (voice cue) — say 'wake up' to resume")
            await voice.say("Going quiet. Say wake up when you need me.")
        else:
            # ── once-a-day session verification (voice + face) ─────────────
            today = datetime.date.today()
            if verified["date"] != today:
                verified.update(on=False, date=today)
            voice_ok = (speaker == cfg.user_name) if (vani and vani.ready and vani.db) else True
            if not verified["on"]:
                if args.text or (voice_ok and face_ok()):
                    verified["on"] = True
                    await bus.emit("presence", name=cfg.user_name, known=True)
                    await bus.log("session verified — voice and face confirmed")
                else:
                    await bus.log(f"session verification failed (voice={voice_ok}, face={face_ok()})")
                    await voice.say("Before we begin — face the camera and say that "
                                    "again for me, Boss. Voice and face, once a day.")
                    if cfg.followup and svc["ears"]:
                        await voice.wait_until_quiet()
                        await asyncio.sleep(cfg.echo_settle)
                        svc["ears"].trigger()
                    return
            elif speaker and speaker != cfg.user_name and not face_ok():
                # verified session, but an unknown voice with no verified face in
                # sight — camera verification negative → re-lock.
                verified["on"] = False
                await bus.log("session re-locked: unknown voice, no verified face")
                await voice.say("I don't recognize that voice, and I can't see "
                                "Boss. Verification required.")
                return
            tag = "[Session: verified] " if verified["on"] else ""
            await brain.handle_user_text(tag + text, speaker)

        if cfg.followup and svc["ears"] and awake():
            await voice.wait_until_quiet()
            await asyncio.sleep(cfg.echo_settle)
            svc["ears"].trigger()

    greeted_on: dict[str, datetime.date] = {}

    async def on_known(name: str) -> None:
        brain.note_sighting(name)
        await bus.emit("presence", name=name, known=True)
        today = datetime.date.today()
        first_of_day = greeted_on.get(name) != today
        if first_of_day:
            greeted_on[name] = today
            await voice.say(_greeting(name))
        else:
            await voice.say(f"Hi, {name}.")
        await voice.wait_until_quiet()
        await asyncio.sleep(cfg.echo_settle)
        if svc["ears"]:
            svc["ears"].trigger()

    async def on_guest() -> None:
        brain.note_sighting("an unrecognized guest")
        await bus.emit("presence", name="Guest", known=False)
        if cfg.nandi_greet_guests:
            await voice.say("Welcome. I don't believe we've met.")

    def start_awake_services() -> None:
        heim = Nandi(cfg, bus, on_known, on_guest, on_seen=brain.note_sighting,
                        is_speaking=voice.busy, on_barge_in=voice.stop)
        _tool_ctx["nandi"] = heim
        svc["nandi"] = heim
        svc["tasks"] = [asyncio.create_task(heim.run())]
        if not args.text:
            ears = Ears(cfg, bus, on_utterance, hot=presence_hot, vani=vani,
                        identity_hint=identity_hint, is_speaking=shiva_talking,
                        clap_feed=clapdet.feed)
            # Vani runs only when it matters: pre-verification, or when the
            # verified face ISN'T in sight (re-lock guard). Saves ~1s/utterance.
            ears.need_speaker = lambda: not (verified["on"] and face_ok())
            svc["ears"] = ears
            svc["tasks"].append(asyncio.create_task(ears.run()))

    def stop_awake_services() -> None:
        if svc["nandi"]:
            svc["nandi"].stop()
        if svc["ears"]:
            svc["ears"].stop()
        svc["ears"] = None
        svc["nandi"] = None
        svc["tasks"] = []

    # ── wake / sleep sequences ─────────────────────────────────────────────
    async def wake_sequence() -> None:
        state["mode"] = "awake"
        await bus.emit("odinmode", value="awake")
        # "thinking" while the anthem plays: keeps the hot-mic shut so the
        # music itself is never captured, and shows the HUD warming up.
        await bus.state("thinking")
        music = None
        if cfg.wake_music and Path(cfg.wake_music).exists():
            try:
                n = max(4.0, cfg.wake_music_seconds)
                music = await asyncio.create_subprocess_exec(
                    FFPLAY, "-autoexit", "-nodisp", "-loglevel", "quiet",
                    "-t", str(n), "-af", f"afade=t=out:st={n - 4:.1f}:d=4",
                    cfg.wake_music)
            except Exception as e:
                await bus.log(f"wake music unavailable ({e}) — rising in silence")
        # the song is the warm-up window: windows rise, models load, senses arm
        await asyncio.sleep(1.2)
        open_window("world.html" if cfg.primary_screen == "world" else "connectors.html")
        await asyncio.sleep(1.6)
        open_window("index.html")
        greeted_on[cfg.user_name] = datetime.date.today()  # ritual greets; Nandi says just "Hi"
        start_awake_services()          # whisper/vani/nandi warm during the song
        await voice.warm()              # kokoro hot before the first word
        await bus.log("senses warmed — waiting on the anthem")
        if music:
            with contextlib.suppress(Exception):
                await music.wait()
        await voice.say(cfg.wake_greeting)
        await bus.state("idle")
        await bus.log("SHIVA is awake — all senses online")

    async def sleep_sequence() -> None:
        await voice.say("Going dark, Boss. Clap twice and say wake up when you need me.")
        await voice.wait_until_quiet()
        state["mode"] = "asleep"
        await bus.emit("odinmode", value="asleep")
        stop_awake_services()
        await asyncio.sleep(1.0)   # let mic/camera threads wind down
        close_aux_windows()
        await bus.state("idle")
        await bus.log("SHIVA sleeps — sentinel on watch")
        asyncio.create_task(standby_cycle())

    async def standby_cycle() -> None:
        if args.text:
            return  # typed mode: "wake" via stdin
        sent = Sentinel(cfg, bus)
        if await sent.run_asleep():
            await wake_sequence()

    # ── HUD messages & stdin ───────────────────────────────────────────────
    async def on_client_message(msg: dict) -> None:
        if msg.get("kind") == "trigger_ears":
            if svc["ears"] and awake():
                svc["ears"].trigger()   # push-to-talk from a screen (Space in the World)
            return
        if msg.get("kind") == "text_input":
            text = (msg.get("text") or "").strip()
            if text:
                await voice.stop()
                await bus.transcript("user", text)
                if not awake():
                    if any(w in text.lower() for w in ("wake", "rise")):
                        await wake_sequence()
                    return
                await brain.handle_user_text(text)
            return
        await voice.handle_hud_message(msg)

    bus.on_client_message = on_client_message

    async def stdin_loop() -> None:
        loop = asyncio.get_running_loop()
        while True:
            line = await loop.run_in_executor(None, sys.stdin.readline)
            if not line:
                return
            line = line.strip()
            if not line:
                if svc["ears"]:
                    svc["ears"].trigger()
                continue
            low = line.lower()
            if not awake():
                if low in ("wake", "wake up", "wakeup"):
                    await wake_sequence()
                continue
            if low in ("shutdown", "sleep"):
                await sleep_sequence()
                continue
            if low.startswith("demo"):
                from .tools_demo import handle_demo_command
                if await handle_demo_command(line, brain, bus):
                    continue
            await bus.transcript("user", line)
            await brain.handle_user_text(line)

    # ── boot ───────────────────────────────────────────────────────────────
    tasks = [
        asyncio.create_task(voice.run()),
        asyncio.create_task(shruti.run()) if (shruti := Shruti(cfg, bus, brain)) else None,
        asyncio.create_task(Drishti(cfg, bus).run()),
        asyncio.create_task(reminders.run()),
        asyncio.create_task(watchtower.run()),
        asyncio.create_task(brain.watch_council()),
        asyncio.create_task(kaala.run()),
        asyncio.create_task(stdin_loop()),
    ]
    tasks = [t for t in tasks if t]

    # SHIVA opens his own Sanctum — no reliance on the launcher's Chrome call.
    if sanctum_missing():
        open_window("sanctum.html")

    if awake():
        await bus.state("idle")
        await bus.emit("odinmode", value="awake")
        await voice.say(f"{cfg.assistant_name} online. Good day, {cfg.user_name}.")
        start_awake_services()
    else:
        await bus.state("idle")
        await bus.emit("odinmode", value="asleep")
        await bus.log("standby — clap twice and say “wake up”")
        asyncio.create_task(standby_cycle())

    try:
        await asyncio.gather(*tasks)
    finally:
        await brain.close()


if __name__ == "__main__":
    with contextlib.suppress(KeyboardInterrupt):
        asyncio.run(main())
